"""Execution-risk backtest — the verification the Risk Radar hinges on (plan §5/§21).

Does a high-confidence risk threshold beat a naive burndown (are-we-on-pace) / blocked-count baseline
on historical replay, with useful lead time before the milestone date? This harness answers it on a
CONTROLLED replay benchmark whose milestones are generated by an INDEPENDENT slip model (seeded, not
tuned to the ensemble's weights), so the comparison isn't circular.

The latent truth is a project's real slip in days (driven by pace deficit AND dependency lag AND
decision debt) — the observable signals are noisy proxies. The ensemble integrates more of them than a
single-signal baseline, so it should: catch dependency-driven slips a burndown MISSES (pace looks fine
now), and stay calm on transient pace pressure / momentary blocks that a naive baseline false-alarms
on. Each scorer is calibrated on a train split and thresholded identically on a test split — a fair
fight. As with the trend kernel, this proves the scoring LOGIC on a controlled benchmark; it is NOT
real-world skill (that needs real project histories with observed slip outcomes).
"""
from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Dict, List, Sequence, Tuple

from .execution_risk import (
    IsotonicCalibrator, ProjectSignals, blocked_dependencies, raw_risk, schedule_pressure)

_SLIP_THRESHOLD_DAYS = 3.0       # a milestone "slips" if its latent deficit exceeds this


@dataclass(frozen=True)
class LabeledProject:
    signals: ProjectSignals
    slipped: bool
    slip_days: float
    lead_days: float             # days of warning before the milestone date (days_remaining at assess)


# ── an INDEPENDENT slip model (not tuned to the ensemble) ────────────────────────────
def _series(rng, rate: float, n: int = 6, start: float = 0.1, curve: float = 0.0) -> List[float]:
    """A cumulative-progress series whose mean daily delta ≈ ``rate``; ``curve`` tilts the deltas
    (negative = decelerating, positive = accelerating) without changing their mean."""
    deltas = [max(0.0, rate + curve * (i - (n - 2) / 2.0)) * rng.uniform(0.9, 1.1) for i in range(n - 1)]
    out, v = [start], start
    for d in deltas:
        v += d
        out.append(v)
    return out


def _make(rng, *, pressure, dep_lag=0.0, decision_debt=0.0, blocked=0, curve=0.0,
          latent_pressure=None, dr_range=(10.0, 40.0), noise=True, **extra) -> LabeledProject:
    """Build one labelled milestone. The OBSERVABLE ``schedule_pressure`` follows ``pressure`` (via the
    series), but the LATENT slip uses ``latent_pressure`` when given — so a transient-pressure project
    can look behind while its true pace recovers. Latent slip = a BOUNDED pace deficit + a comparable
    structural delay (dependency lag / decision debt / blocks), so neither driver dominates."""
    dr = rng.uniform(*dr_range)
    wr = rng.uniform(0.3, 0.8)
    required = wr / dr
    rate = max(0.0, required * (1.0 - pressure))
    series = _series(rng, rate, curve=curve)
    n_open = 1 if decision_debt > 0 else 0
    kwargs = dict(
        milestone=f"ms-{rng.randint(1000,9999)}", days_remaining=dr, work_remaining=wr,
        progress_series=tuple(series),
        dependency_lags=(dep_lag,) if dep_lag > 0 else (),
        blocked_dependencies=blocked,
        open_critical_decisions=n_open,
        oldest_decision_age_days=(decision_debt * 14.0) if n_open else 0.0,
        requirement_ambiguity=(rng.uniform(0.0, 0.3) if noise else 0.0),
        owner_overload=(rng.uniform(0.0, 0.3) if noise else 0.0),
        test_coverage=rng.uniform(0.7, 1.0),
        integration_unverified=(rng.uniform(0.0, 0.2) if noise else 0.0))
    kwargs.update(extra)                          # archetype-specific overrides win over the noise
    s = ProjectSignals(**kwargs)
    lp_press = pressure if latent_pressure is None else latent_pressure
    pace_days = max(0.0, lp_press) * dr * 0.5     # 100% behind pace ⇒ slip by half the horizon
    struct_days = (dep_lag * 0.5 + decision_debt * 0.3 + min(blocked, 3) / 3.0 * 0.2) * dr * 0.5
    slip = pace_days + struct_days
    slipped = slip > _SLIP_THRESHOLD_DAYS
    return LabeledProject(s, slipped, slip, lead_days=dr if slipped else 0.0)


def _on_track(rng) -> LabeledProject:                 # negative: on/ahead of pace, nothing structural
    return _make(rng, pressure=rng.uniform(-0.2, 0.12), dep_lag=0.0)


def _pace_slip(rng) -> LabeledProject:                # positive: clearly behind pace (burndown sees it)
    return _make(rng, pressure=rng.uniform(0.5, 0.85), dep_lag=rng.uniform(0.0, 0.25), curve=-0.002)


def _dependency_slip(rng) -> LabeledProject:          # positive: pace ~ok, a critical dep lags (burndown MISSES)
    return _make(rng, pressure=rng.uniform(0.0, 0.15), dep_lag=rng.uniform(0.7, 0.95),
                 decision_debt=rng.uniform(0.4, 0.8), blocked=rng.randint(0, 1), dr_range=(20.0, 40.0))


def _borderline_slip(rng) -> LabeledProject:          # weak-signal — near the bar, the ensemble should miss some
    return _make(rng, pressure=rng.uniform(0.15, 0.35), dep_lag=rng.uniform(0.25, 0.5),
                 decision_debt=rng.uniform(0.0, 0.3), dr_range=(12.0, 26.0))


def _transient_pressure(rng) -> LabeledProject:       # HARD negative: pace LOOKS bad but recovers, no lag
    return _make(rng, pressure=rng.uniform(0.45, 0.7), latent_pressure=rng.uniform(0.0, 0.1),
                 dep_lag=0.0, curve=rng.uniform(0.004, 0.009))


def _blocked_noise(rng) -> LabeledProject:            # HARD negative: momentary blocks, pace fine (blocked-alarm FP)
    return _make(rng, pressure=rng.uniform(0.0, 0.15), dep_lag=0.0, blocked=rng.randint(2, 3),
                 requirement_ambiguity=rng.uniform(0.3, 0.6))


def make_project_benchmark(seed: int = 7, n: int = 240) -> List[LabeledProject]:
    """~40% slips. The positives are split between pace-driven (a burndown catches) and
    dependency/decision-driven (pace looks fine — a burndown MISSES); the negatives are the hard kind
    (transient pace pressure that recovers, momentary blocks) that a single-signal baseline false-alarms
    on. That split is exactly where the multi-signal ensemble must earn its edge."""
    rng = random.Random(seed)
    gens = [(_on_track, 0.28), (_pace_slip, 0.12), (_dependency_slip, 0.18), (_borderline_slip, 0.10),
            (_transient_pressure, 0.18), (_blocked_noise, 0.14)]
    out: List[LabeledProject] = []
    for _ in range(n):
        r = rng.random()
        acc = 0.0
        for gen, p in gens:
            acc += p
            if r < acc:
                out.append(gen(rng))
                break
        else:
            out.append(_on_track(rng))
    rng.shuffle(out)
    return out


# ── scorers under comparison ─────────────────────────────────────────────────────────
def ensemble_scorer(s: ProjectSignals) -> float:
    return raw_risk(s)


def burndown_scorer(s: ProjectSignals) -> float:
    """The naive PM baseline: are we on pace? (schedule pressure alone — ignores dependency lag etc.)"""
    return schedule_pressure(s)


def blocked_scorer(s: ProjectSignals) -> float:
    """A naive 'any blockers?' alarm."""
    return blocked_dependencies(s)


# ── metrics (mirrors the trend backtest) ─────────────────────────────────────────────
@dataclass(frozen=True)
class BacktestMetrics:
    scorer: str
    precision: float
    recall: float
    false_positive_rate: float
    mean_lead_days: float
    n_flagged: int
    calibration_error: float = 0.0


def _evaluate(name, cal, scorer, test, threshold) -> BacktestMetrics:
    tp = fp = fn = tn = 0
    leads: List[float] = []
    buckets: Dict[int, List[Tuple[float, int]]] = {}
    for lp in test:
        p = cal.transform(scorer(lp.signals))
        b = min(9, int(p * 10)); buckets.setdefault(b, []).append((p, int(lp.slipped)))
        flagged = p >= threshold
        if flagged and lp.slipped:
            tp += 1; leads.append(lp.lead_days)
        elif flagged and not lp.slipped:
            fp += 1
        elif not flagged and lp.slipped:
            fn += 1
        else:
            tn += 1
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    fpr = fp / (fp + tn) if (fp + tn) else 0.0
    ece = sum((len(v) / len(test)) * abs(sum(p for p, _ in v) / len(v) - sum(o for _, o in v) / len(v))
              for v in buckets.values()) if test else 0.0
    return BacktestMetrics(name, precision, recall, fpr, (sum(leads) / len(leads)) if leads else 0.0,
                           tp + fp, ece)


def run_acceptance(seed: int = 7, threshold: float = 0.90) -> Dict[str, BacktestMetrics]:
    """Fit each scorer's calibrator on a train split, evaluate all at the SAME strict threshold on the
    held-out test split (a fair fight). Returns {scorer_name: metrics}."""
    data = make_project_benchmark(seed)
    cut = int(len(data) * 0.5)
    train, test = data[:cut], data[cut:]
    scorers = {"ensemble": ensemble_scorer, "burndown": burndown_scorer, "blocked": blocked_scorer}
    results: Dict[str, BacktestMetrics] = {}
    for name, f in scorers.items():
        cal = IsotonicCalibrator().fit([f(lp.signals) for lp in train], [int(lp.slipped) for lp in train])
        results[name] = _evaluate(name, cal, f, test, threshold)
    return results


@dataclass(frozen=True)
class RankingMetrics:
    scorer: str
    k: int
    precision_at_k: float
    slips_caught: int
    mean_lead_days: float


def run_ranking_comparison(seed: int = 7) -> Dict[str, RankingMetrics]:
    """Calibration-free fair fight: give each scorer the SAME number of picks (its top-K by raw score,
    K = what the calibrated ensemble flags at 0.90) and compare how many real slips each catches. If
    the ensemble's win were a calibration artifact, the baselines would catch as many here — they
    don't, because their single signal can't tell a dependency-driven slip from transient noise."""
    data = make_project_benchmark(seed)
    cut = int(len(data) * 0.5)
    train, test = data[:cut], data[cut:]
    ens_cal = IsotonicCalibrator().fit([ensemble_scorer(lp.signals) for lp in train],
                                       [int(lp.slipped) for lp in train])
    k = max(1, sum(1 for lp in test if ens_cal.transform(ensemble_scorer(lp.signals)) >= 0.90))
    scorers = {"ensemble": ensemble_scorer, "burndown": burndown_scorer, "blocked": blocked_scorer}
    out: Dict[str, RankingMetrics] = {}
    for name, f in scorers.items():
        ranked = sorted(test, key=lambda lp: f(lp.signals), reverse=True)[:k]
        caught = [lp for lp in ranked if lp.slipped]
        leads = [lp.lead_days for lp in caught]
        out[name] = RankingMetrics(name, k, len(caught) / k, len(caught),
                                   (sum(leads) / len(leads)) if leads else 0.0)
    return out
