"""Trend-intelligence backtest — the verification the whole feature hinges on (plan §10/§28/§30).

Does a high-confidence threshold beat a momentum / search-only baseline on historical replay, with
useful lead time? This harness answers it on a **controlled replay benchmark** whose candidates are
generated by an INDEPENDENT emergence/noise model (seeded; not tuned to the ensemble's weights), so
the comparison isn't circular. Each scorer is calibrated on a train split and thresholded identically
on a test split — a fair fight; the ensemble should win because its raw signal *separates* true
emergence from one-platform / seasonal / manipulated spikes, which momentum cannot.

Scope of the claim this proves: the scoring **logic** discriminates emergence patterns from noise
patterns as designed. It is NOT evidence of real-world skill — that needs live Reddit/YouTube/search
evidence and a real labeled outcome set (the next gate before any accuracy claim or launch).
"""
from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Callable, Dict, List, Sequence, Tuple

from .trend_intelligence import (
    IsotonicCalibrator, TrendCandidate, raw_future_confidence, velocity)


@dataclass(frozen=True)
class LabeledCandidate:
    candidate: TrendCandidate
    broke_out: bool          # did it cross the breakout threshold within the horizon?
    lead_days: float         # if it broke out, days between the cutoff and the breakout (lead time)


# ── an INDEPENDENT emergence/noise generator (not tuned to the ensemble) ────────────
def _accelerating(rng, base, n=8) -> List[float]:
    v, g = base, rng.uniform(0.18, 0.35)
    out = [v]
    for _ in range(n - 1):
        g += rng.uniform(0.03, 0.08)                     # growth speeds up (acceleration)
        v = max(0.0, v * (1 + g) * rng.uniform(0.9, 1.1))
        out.append(v)
    return out


def _flat(rng, level, n=8) -> List[float]:
    return [max(0.0, level * rng.uniform(0.9, 1.1)) for _ in range(n)]


def _spike(rng, base, peak, n=8) -> List[float]:
    # a rising ramp into a jump — so its *velocity* overlaps a real breakout's (momentum can't tell
    # them apart on growth alone); what gives it away is that it's one platform, late, uncorroborated.
    out = _flat(rng, base, n)
    for i in range(max(0, n - 4), n - 2):
        out[i] = base * rng.uniform(1.3, 2.2) * (i - (n - 5))
    out[-2] = peak * rng.uniform(0.7, 1.0)
    out[-1] = peak * rng.uniform(0.9, 1.1)
    return out


def _seasonal(rng, base, n=8) -> List[float]:
    return [max(0.0, base * (1.4 if i >= n - 3 else 1.0) * rng.uniform(0.9, 1.1)) for i in range(n)]


def _breakout(rng) -> LabeledCandidate:
    # ~30% are BORDERLINE true trends: weak early signal (2 sources, few/no outliers, some
    # competition) — the ensemble should MISS a fair share of these, so recall is realistically < 1.
    borderline = rng.random() < 0.30
    n_src = 2 if borderline else rng.randint(2, 3)
    sources = rng.sample(["reddit", "youtube", "search", "hn"], n_src)
    series = {s: _accelerating(rng, base=rng.uniform(1, 4)) for s in sources}
    outliers = tuple(rng.uniform(3, 12) for _ in range(rng.randint(0, 1) if borderline else rng.randint(2, 4)))
    c = TrendCandidate(
        entity=f"breakout-{rng.randint(1000,9999)}", series=series, creator_outliers=outliers,
        question_growth=rng.uniform(0.1, 0.5) if borderline else rng.uniform(0.5, 1.2),
        geo_count=rng.randint(1, 2) if borderline else rng.randint(2, 6),
        content_supply=rng.uniform(0.0, 0.3), competitor_authority=rng.uniform(0.2, 0.5) if borderline else rng.uniform(0.0, 0.3),
        keyword_competition=rng.uniform(0.0, 0.3), ad_density=rng.uniform(0.0, 0.2),
        brand_penetration=rng.uniform(0.0, 0.2), bot_ratio=rng.uniform(0.0, 0.2))
    return LabeledCandidate(c, True, lead_days=rng.uniform(20, 60))


def _single_source_spike(rng) -> LabeledCandidate:
    # a hard negative that FOOLS momentum: one platform spikes hard. ~40% are LEAKY — a faint second
    # source rises and manipulation is low — so they occasionally slip past the ensemble too (⇒ its
    # precision is realistically < 1, and the win over momentum is a gap, not a blowout).
    leaky = rng.random() < 0.40
    srcs = rng.sample(["reddit", "youtube", "search"], 2 if leaky else 1)
    series = {srcs[0]: _spike(rng, base=2, peak=rng.uniform(12, 26))}
    if leaky:
        series[srcs[1]] = _accelerating(rng, base=rng.uniform(1, 2))    # a weak corroborator
    c = TrendCandidate(
        entity=f"spike-{rng.randint(1000,9999)}", series=series,
        creator_outliers=(rng.uniform(3, 6),) if leaky else (),
        question_growth=rng.uniform(0.0, 0.3), geo_count=1 if not leaky else 2,
        single_source_spike=not leaky, bot_ratio=rng.uniform(0.1, 0.3) if leaky else rng.uniform(0.3, 0.7),
        competitor_authority=rng.uniform(0.1, 0.4))
    return LabeledCandidate(c, False, 0.0)


def _seasonal_negative(rng) -> LabeledCandidate:
    srcs = rng.sample(["reddit", "youtube", "search"], 2)
    c = TrendCandidate(
        entity=f"seasonal-{rng.randint(1000,9999)}", series={s: _seasonal(rng, base=8) for s in srcs},
        question_growth=rng.uniform(0.1, 0.4), geo_count=rng.randint(1, 2),
        seasonal_recurrence=rng.uniform(0.6, 0.9), competitor_authority=rng.uniform(0.3, 0.6),
        content_supply=rng.uniform(0.3, 0.6))
    return LabeledCandidate(c, False, 0.0)


def _saturated_or_flat(rng) -> LabeledCandidate:
    if rng.random() < 0.5:                                # already-crowded topic
        srcs = rng.sample(["reddit", "youtube", "search"], 2)
        c = TrendCandidate(entity=f"sat-{rng.randint(1000,9999)}",
                           series={s: _flat(rng, level=30) for s in srcs},
                           content_supply=rng.uniform(0.7, 0.95), competitor_authority=rng.uniform(0.7, 0.95),
                           ad_density=rng.uniform(0.6, 0.9), keyword_competition=rng.uniform(0.6, 0.9))
    else:                                                 # plain low-signal noise
        c = TrendCandidate(entity=f"flat-{rng.randint(1000,9999)}",
                           series={"reddit": _flat(rng, level=3), "search": _flat(rng, level=2)})
    return LabeledCandidate(c, False, 0.0)


def make_replay_benchmark(seed: int = 7, n: int = 240) -> List[LabeledCandidate]:
    """~35% true breakouts; the negatives are mostly the HARD kind (single-source / seasonal spikes)
    that fool a momentum baseline, which is exactly where the ensemble must earn its precision."""
    rng = random.Random(seed)
    out: List[LabeledCandidate] = []
    for _ in range(n):
        r = rng.random()
        if r < 0.35:
            out.append(_breakout(rng))
        elif r < 0.60:
            out.append(_single_source_spike(rng))
        elif r < 0.80:
            out.append(_seasonal_negative(rng))
        else:
            out.append(_saturated_or_flat(rng))
    rng.shuffle(out)
    return out


# ── scorers under comparison ────────────────────────────────────────────────────────
def ensemble_scorer(c: TrendCandidate) -> float:
    return raw_future_confidence(c)


def momentum_scorer(c: TrendCandidate) -> float:
    return velocity(c)                                   # velocity/acceleration only (plan §5A)


def search_only_scorer(c: TrendCandidate) -> float:
    """Google-Trends-style single-signal: the search source's growth alone."""
    from .trend_intelligence import _growth_rate, _clamp
    s = c.series.get("search")
    return _clamp(_growth_rate(s)) if s else 0.0


# ── metrics ──────────────────────────────────────────────────────────────────────────
@dataclass(frozen=True)
class BacktestMetrics:
    scorer: str
    precision: float
    recall: float
    false_positive_rate: float
    mean_lead_days: float
    n_flagged: int
    calibration_error: float = 0.0


def _evaluate(name: str, cal: IsotonicCalibrator, scorer, test: Sequence[LabeledCandidate],
              threshold: float) -> BacktestMetrics:
    tp = fp = fn = tn = 0
    leads: List[float] = []
    buckets: Dict[int, List[Tuple[float, int]]] = {}
    for lc in test:
        p = cal.transform(scorer(lc.candidate))
        b = min(9, int(p * 10)); buckets.setdefault(b, []).append((p, int(lc.broke_out)))
        flagged = p >= threshold
        if flagged and lc.broke_out:
            tp += 1; leads.append(lc.lead_days)
        elif flagged and not lc.broke_out:
            fp += 1
        elif not flagged and lc.broke_out:
            fn += 1
        else:
            tn += 1
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    fpr = fp / (fp + tn) if (fp + tn) else 0.0
    ece = sum((len(v) / len(test)) * abs(sum(p for p, _ in v) / len(v) - sum(o for _, o in v) / len(v))
              for v in buckets.values()) if test else 0.0
    return BacktestMetrics(name, precision, recall, fpr, (sum(leads) / len(leads)) if leads else 0.0,
                           tp + fp, ece)


def run_acceptance(seed: int = 7, threshold: float = 0.90) -> Dict[str, BacktestMetrics]:
    """Fit each scorer's calibrator on a train split, then evaluate all at the SAME strict threshold
    on the held-out test split (a fair fight). Returns {scorer_name: metrics}."""
    data = make_replay_benchmark(seed)
    cut = int(len(data) * 0.5)
    train, test = data[:cut], data[cut:]
    scorers = {"ensemble": ensemble_scorer, "momentum": momentum_scorer, "search_only": search_only_scorer}
    results: Dict[str, BacktestMetrics] = {}
    for name, f in scorers.items():
        cal = IsotonicCalibrator().fit([f(lc.candidate) for lc in train],
                                       [int(lc.broke_out) for lc in train])
        results[name] = _evaluate(name, cal, f, test, threshold)
    return results


@dataclass(frozen=True)
class RankingMetrics:
    """Matched-volume ranking quality: if a scorer is allowed to flag the SAME NUMBER of candidates
    the ensemble did (its top-K by raw score), how many are real breakouts? This removes the
    threshold/calibration advantage entirely and asks only: is the ranking better?"""
    scorer: str
    k: int                       # candidates flagged (identical across scorers by construction)
    precision_at_k: float        # of the top-K, fraction that truly broke out
    breakouts_caught: int
    mean_lead_days: float


def run_ranking_comparison(seed: int = 7) -> Dict[str, RankingMetrics]:
    """A calibration-free fair fight. Rank the test split by each scorer's RAW score, take the top-K
    where K = the number the ensemble would flag at 0.90, and compare precision@K. If the ensemble's
    win were an artifact of calibration or threshold choice, momentum would catch just as many here —
    it doesn't, because its *ranking* cannot tell one-platform/seasonal spikes from real emergence."""
    data = make_replay_benchmark(seed)
    cut = int(len(data) * 0.5)
    train, test = data[:cut], data[cut:]
    # K = how many the (calibrated) ensemble flags at the strict threshold — a realistic operating volume.
    ens_cal = IsotonicCalibrator().fit([ensemble_scorer(lc.candidate) for lc in train],
                                       [int(lc.broke_out) for lc in train])
    k = sum(1 for lc in test if ens_cal.transform(ensemble_scorer(lc.candidate)) >= 0.90)
    k = max(k, 1)
    scorers = {"ensemble": ensemble_scorer, "momentum": momentum_scorer, "search_only": search_only_scorer}
    out: Dict[str, RankingMetrics] = {}
    for name, f in scorers.items():
        ranked = sorted(test, key=lambda lc: f(lc.candidate), reverse=True)[:k]
        caught = [lc for lc in ranked if lc.broke_out]
        leads = [lc.lead_days for lc in caught]
        out[name] = RankingMetrics(name, k, len(caught) / k, len(caught),
                                   (sum(leads) / len(leads)) if leads else 0.0)
    return out
