"""Intelligence families (Intelligence-APIs plan §5–§10).

Each family is a thin set of deterministic/statistical functions over the canonical business graph,
served to the broker as a capability. Supplier is the first (Phase 1): reliability metrics computed
straight from the tenant's own PO / confirmation / receipt events — no external provider needed, and
reproducible as-of a past decision time (leakage-safe).
"""
from .supplier import (
    ConfirmationReliability,
    DeliveryReliability,
    confirmation_reliability,
    delivery_reliability,
)
from .supplier_broker import (
    InMemorySupplyEvents,
    SupplierMetricsProvider,
    SupplyEventSource,
    supplier_registry,
    supplier_synthesize,
)
from .order import (
    Blocker,
    InMemoryOrderGraph,
    LineageNode,
    OrderLineage,
    PromiseFeasibility,
    order_blockers,
    order_lineage,
    promise_feasibility,
)
from .order_broker import OrderIntelligenceProvider, order_registry, order_synthesize
from .supplier_resolution import (
    GleifSupplierResolver,
    InternalSupplierResolver,
    SupplierResolution,
    resolve_supplier,
    supplier_resolution_registry,
    supplier_resolution_synthesize,
)
from .supply import (
    BomComponent,
    BomImpact,
    RequiredByFeasibility,
    SafetyStockRecommendation,
    ShortageProjection,
    StockoutConsequence,
    SubstituteOption,
    bom_closure,
    bom_impact,
    required_by_feasibility,
    safety_stock,
    shortage_risk,
    stockout_consequence,
    substitute_availability,
)
from .supply_broker import SupplyGraph, SupplyIntelligenceProvider, supply_registry, supply_synthesize
from .process import (
    Anomaly,
    Bottleneck,
    CycleBenchmark,
    NextEvent,
    WhyStuck,
    anomaly,
    bottlenecks,
    cycle_benchmark,
    next_event,
    why_stuck,
)
from .process_broker import (
    ProcessEventLog,
    ProcessIntelligenceProvider,
    process_registry,
    process_synthesize,
)
from .counterparty import (
    CounterpartyProvider,
    CounterpartyRecords,
    PaymentBehavior,
    RelationshipGraph,
    counterparty_registry,
    counterparty_synthesize,
    payment_behavior,
    relationship_graph,
)
from .asset import (
    asset_identity, failure_risk, maintenance_risk, parts_risk, replacement_compatibility, service_history,
)
from .asset_broker import AssetGraph, AssetIntelligenceProvider, asset_registry, asset_synthesize
from .revenue_broker import (
    InMemoryRevenueState,
    QuoteInputs,
    RevenueIntelligenceProvider,
    RevenueStateSource,
    revenue_registry,
    revenue_synthesize,
)
from .revenue_sources import TwentyLeakageState, twenty_revenue_registry

__all__ = [
    "DeliveryReliability",
    "ConfirmationReliability",
    "delivery_reliability",
    "confirmation_reliability",
    "SupplyEventSource",
    "InMemorySupplyEvents",
    "SupplierMetricsProvider",
    "supplier_registry",
    "supplier_synthesize",
    "OrderLineage",
    "LineageNode",
    "Blocker",
    "PromiseFeasibility",
    "InMemoryOrderGraph",
    "order_lineage",
    "order_blockers",
    "promise_feasibility",
    "OrderIntelligenceProvider",
    "order_registry",
    "order_synthesize",
    "SupplierResolution",
    "resolve_supplier",
    "InternalSupplierResolver",
    "GleifSupplierResolver",
    "supplier_resolution_registry",
    "supplier_resolution_synthesize",
    "BomComponent",
    "RequiredByFeasibility",
    "ShortageProjection",
    "BomImpact",
    "SubstituteOption",
    "StockoutConsequence",
    "SafetyStockRecommendation",
    "bom_closure",
    "required_by_feasibility",
    "shortage_risk",
    "bom_impact",
    "substitute_availability",
    "stockout_consequence",
    "safety_stock",
    "SupplyGraph",
    "SupplyIntelligenceProvider",
    "supply_registry",
    "supply_synthesize",
    "Bottleneck",
    "CycleBenchmark",
    "NextEvent",
    "WhyStuck",
    "Anomaly",
    "bottlenecks",
    "cycle_benchmark",
    "next_event",
    "why_stuck",
    "anomaly",
    "ProcessEventLog",
    "ProcessIntelligenceProvider",
    "process_registry",
    "process_synthesize",
    "PaymentBehavior",
    "RelationshipGraph",
    "payment_behavior",
    "relationship_graph",
    "CounterpartyRecords",
    "CounterpartyProvider",
    "counterparty_registry",
    "counterparty_synthesize",
    "asset_identity",
    "service_history",
    "failure_risk",
    "maintenance_risk",
    "parts_risk",
    "replacement_compatibility",
    "AssetGraph",
    "AssetIntelligenceProvider",
    "asset_registry",
    "asset_synthesize",
    "QuoteInputs",
    "RevenueStateSource",
    "InMemoryRevenueState",
    "RevenueIntelligenceProvider",
    "revenue_registry",
    "revenue_synthesize",
    "TwentyLeakageState",
    "twenty_revenue_registry",
]
